# Generated by Django 3.2.7 on 2021-10-01 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('products_ordered', models.CharField(max_length=300)),
                ('name', models.CharField(max_length=30)),
                ('email_address', models.CharField(max_length=50)),
                ('phone_number', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=30)),
                ('country', models.CharField(max_length=50)),
                ('first_address', models.CharField(max_length=300)),
                ('second_address', models.CharField(max_length=300)),
                ('tracker', models.CharField(choices=[('Your Order has been Recieved', 'Your Order has been Recieved'), ('Packed', 'Packed'), ('Ship', 'Ship'), ('In your City', 'In your City'), ('Recieved By You', 'Recieved By You')], default='Your Order has been Recieved', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('price', models.IntegerField()),
                ('d_price', models.IntegerField()),
                ('brand', models.CharField(max_length=30)),
                ('description', models.CharField(default='', max_length=3000)),
                ('about_1', models.CharField(max_length=300)),
                ('about_2', models.CharField(max_length=300)),
                ('about_3', models.CharField(max_length=300)),
                ('category', models.CharField(choices=[('shoes', 'shoes'), ('mobile_accessories', 'mobile_accessories'), ('caps', 'caps'), ('watches', 'watches')], default='', max_length=20)),
                ('image', models.ImageField(upload_to='product_images')),
            ],
        ),
    ]
